README.md
=> feat(all): update figma links in readme

packages/ui-library/src/components/actions/buttons/icon-button/index.stories.ts, packages/ui-library/src/components/actions/buttons/text-button/index.stories.ts, packages/ui-library/src/components/feedback/loader/index.stories.ts, packages/ui-library/src/components/feedback/tooltip/index.stories.ts, packages/ui-library/src/components/feedback/tooltip/tooltip-bubble/index.stories.ts, packages/ui-library/src/components/forms/checkbox/index.stories.ts, packages/ui-library/src/components/forms/number-input/index.stories.ts, packages/ui-library/src/components/forms/radio/radio-input-group/index.stories.ts, packages/ui-library/src/components/forms/radio/radio-input/index.stories.ts, packages/ui-library/src/components/forms/select/index.stories.ts, packages/ui-library/src/components/forms/slider/slider-single-value/range-legend-slider/index.stories.ts, packages/ui-library/src/components/forms/slider/slider-single-value/range-slider/index.stories.ts, packages/ui-library/src/components/forms/slider/slider-two-values/range-legend-min-max-slider/index.stories.ts, packages/ui-library/src/components/forms/slider/slider-two-values/range-min-max-slider/index.stories.ts, packages/ui-library/src/components/forms/text-input/index.stories.ts, packages/ui-library/src/components/forms/textarea/index.stories.ts, packages/ui-library/src/components/forms/toggle-switch/index.stories.ts, packages/ui-library/src/components/internal-components/counter/index.stories.ts, packages/ui-library/src/components/internal-components/form-caption-group/form-caption/index.stories.ts, packages/ui-library/src/components/internal-components/form-caption-group/index.stories.ts, packages/ui-library/src/components/internal-components/form-label/index.stories.ts, packages/ui-library/src/components/navigation/tab-bar/index.stories.ts, packages/ui-library/src/components/ui/button-group/index.stories.ts, packages/ui-library/src/components/ui/divider/index.stories.ts, packages/ui-library/src/components/ui/icon/icon-link/index.stories.ts, packages/ui-library/src/components/ui/icon/index.stories.ts
From now on, since we decoupled renderFunction from component instance,
we have to tell storybook from where to get all componentsfrom.
we have to do that for each story
=> added dependencies to story for buttons

doc/GETSTARTED.md
Added bullet about sales deck in project management checklist
=> docs:Update GETSTARTED.md

README.md
- fixed downloadlink to figma file
- removed issues & bugs section, as the new sections under help & feedback, which we added as part of #428 are way more detailed and have a better user-flow
=> docs:Update README.md

packages/js-example-app/src/index.js, packages/ui-library/src/components/textarea/index.stories.ts
=> fix(ui): adjust naming in documentation of Textarea (#485) (#885)

README.md, doc/TESTING.md
=> fix(documentation): create testing documentation (#371)

packages/ui-library/src/components/counter/index.css.ts
=> fix(ui): fix Textarea accessibility violation (#777)

.vscode/settings.json, packages/ui-library/tsconfig.json
Sadly still not enough to replace render functions, but this will be the way to go
=> feat(ui-library): add ts-lit plugin with rules

packages/js-example-app/webpack.prod.js
Render deployment failed, i forgot a tiny thing here
=> fix(js-example-app): prod assets folder

docs/GETSTARTED.md
- myscheduling is not part of the PM Onboarding anymore
=> docs(GETSTARTED): remove myschedling

packages/ui-library/src/components/button-text/index.ts
=> fix(ui-library): accessibility of loading in text-button

packages/js-example-app/src/index.ejs, packages/ui-library/src/components/checkbox/index.stories.ts, packages/ui-library/src/components/checkbox/index.test.ts, packages/ui-library/src/components/checkbox/index.ts
closes #800 
old branch at: https://github.com/deven-org/boiler/tree/fix/800_align-checkbox-props_old
=> fix(ui-library): #800 align checkbox props with design

packages/ui-library/src/components/toggle-switch/index.css.ts, packages/ui-library/src/components/toggle-switch/index.stories.ts, packages/ui-library/src/components/toggle-switch/index.test.ts, packages/ui-library/src/components/toggle-switch/index.ts
old branch at: https://github.com/deven-org/boiler/tree/fix/875-prop-alignment-toggle_old
=> fix(ui-library, storybook): #875 align toggle prop names with design

packages/js-example-app/src/index.ejs, packages/ui-library/src/components/radio/index.stories.ts, packages/ui-library/src/components/radio/index.test.ts, packages/ui-library/src/components/radio/index.ts
closes #823 
old branch at: https://github.com/deven-org/boiler/tree/fix/823-radio-prop-alignment_old
=> fix(ui-library, storybook): #823 radio - align prop names with design

packages/ui-library/src/components/input-field-number/index.stories.ts
=> docs(ui-library): input-field-number, document stepper token usage

packages/ui-library/src/components/input-field-text/index.css.ts, packages/ui-library/src/components/input-field-text/index.ts
=> fix(ui-library): input field text ui fixes

docs/GETSTARTED.md
docs(getstarted): fixed a typo in dev lead touchpoint description
=> docs(getstarted): fixed a typo in dev lead touchpoint description

packages/ui-library/src/components/checkbox/index.css.ts
=> fix(ui-library): #1120 fix checkbox in js example app

packages/ui-library/.storybook/preview.js
=> feat(storybook): add a11y config

packages/ui-library/src/components/checkbox/index.css.ts, packages/ui-library/src/components/input-field-text/index.ts
=> fix(storybook): checkbox size issue

package.json, packages/js-example-app/src/index.server.ts, packages/ui-library/src/components/select/index.css.ts, packages/ui-library/src/components/select/index.stories.ts, packages/ui-library/src/components/select/index.test.ts, packages/ui-library/src/components/select/index.ts, packages/ui-library/src/components/select/renderFunction.ts
=> fix(ui-library): remove slot from select component

packages/js-example-app/src/index.client.ts, packages/js-example-app/src/index.server.ts, packages/ui-library/src/components/radio-group/index.ts, packages/ui-library/src/components/tab-bar-item/index.css.ts, packages/ui-library/src/components/tab-bar-item/index.ts, packages/ui-library/src/components/tab-bar/index.css.ts, packages/ui-library/src/components/tab-bar/index.stories.ts, packages/ui-library/src/components/tab-bar/index.test.ts, packages/ui-library/src/components/tab-bar/index.ts, packages/ui-library/src/index.ts
=> fix(ui-library): 1135 tab component slot

docs/GETSTARTED.md
- updated team overview
- updated and split meetings into regular, optional and paused
=> docs(getstarted): update getstarted

packages/ui-library/src/components/textarea/index.css.ts
=> fix(storybook):  diable resize function

packages/ui-library/src/components/button-icon/index.test.ts, packages/ui-library/src/components/button-text/index.test.ts, packages/ui-library/src/components/input-field-number/index.test.ts, packages/ui-library/src/components/toggle-switch/index.css.ts, packages/ui-library/src/components/toggle-switch/index.ts
closes #1030 
closes #792
closes #505
closes #793
closes #1047
=> fix(ui-library): component toggle-switch fixes

packages/ui-library/src/components/button-text/index.ts, packages/ui-library/src/components/input-field-text/index.ts, packages/ui-library/src/components/textarea/index.ts, packages/ui-library/src/utils/lit/sanitization-controller.ts, packages/ui-library/src/utils/lit/sanitize.ts, packages/ui-library/src/utils/lit/signals.ts
=> feat(ui-library): introduce property sanitizer using preact and controller

CHANGELOG.md, package.json
=> Revert "chore(main): release 0.2.0"

.github/workflows/release.yml
=> Revert "feat(chor): set up pre release setting"

.github/workflows/release.yml
=> feat(release): 0.4.0

.github/workflows/release.yml
=> feat(ci): update release pipeline

.github/workflows/release.yml
=> feat(release): updated release workflow to trigger pr from main
