deven-org/boiler

packages/ui-library/src/components/forms/number-input/index.test.ts, packages/ui-library/src/components/forms/number-input/index.ts
This MR fixes two issues:
- The disappearing stepper button upon two actions:
- Setting the unit to `undefined`
- Setting `readonly` to `true`
It extracts the stepper rendering method out of the conditional rendering of the unit text.
- Placeholder unable to appear because the default value is not undefined
It adds a condition to render the placeholder text for 0 value.
=> NumberInput - Fix the disappearing stepper buttons and hiding placeholder text

LICENSE.md
- Updated year in license.md to 2023-2024
- Also fixed an error, where B01LER was not replacing the full placeholder
=> docs: update year in license

CONTRIBUTING.md
Updated the labels under Tipps to find issues, and added the "core team issue" label, which was newly introduced.
=> docs: update label section in contribute file

packages/ui-library/src/components/forms/radio/index.test.ts, packages/ui-library/src/utils/typesafe-generic-component-renderer.ts
this pr changes the render function to only use dots in two cases:
if the value is an object/array or if the value is a boolean false. 
In both cases, you will not see key/value in storybooks code preview.
Since we want to move away from arrays anyway, this is actually not a problem for us
=> Code snipped fix

.vscode/extensions.json
I just noticed this while setting up vs code for work on the project when I was wondering which of the plugins I should install 🙂 
The name seems to have changed, the [lit-analyzer repo](https://github.com/runem/lit-analyzer) also links to the `runem.lit-plugin` extension (`runem.lit-analyzer` doesn't exist)
=> fix(all): use new name of lit-analyzer extension in vs code recommendations

packages/ui-library/src/components/forms/number-input/index.ts, packages/ui-library/src/components/navigation/tab-bar/index.ts, packages/ui-library/src/components/ui/divider/index.stories.ts, packages/ui-library/src/components/ui/divider/index.test.ts, packages/ui-library/src/components/ui/divider/index.ts
=> consistency property naming between code and documentation for divider (#874)

packages/ui-library/src/components/form-label/index.stories.ts, packages/ui-library/src/components/form-label/index.test.ts, packages/ui-library/src/components/form-label/index.ts, packages/ui-library/src/components/number-input/index.css.ts, packages/ui-library/src/components/number-input/index.stories.ts, packages/ui-library/src/components/number-input/index.test.ts, packages/ui-library/src/components/number-input/index.ts
Issue: #774 
The changes to the label were necessary to preserve the releation between the input and its label, both for the accessibility tree, and for standard browser behaviour (e.g. click on label focuses input)
=> fix 774 number input accessibility

CONTRIBUTING.md
- changed title to "Contributing" and combined intro sections above "Content"
- added icons to main section titles and Content
- removed B01LER Monthly, as it is already mentioned in README
=> docs(general):Update CONTRIBUTING.md

packages/icons/icons-optimized/index.ts, packages/icons/scripts/index.mjs
This changes the `SizelessIcon` type from `string` to the union of valid icon names.
=> fix(icons): auto generated icon type needs const array

packages/ui-library/src/components/form-label/index.stories.ts, packages/ui-library/src/components/form-label/index.test.ts, packages/ui-library/src/components/form-label/index.ts, packages/ui-library/src/components/number-input/index.ts, packages/ui-library/src/components/select/index.ts, packages/ui-library/src/components/text-input/index.stories.ts, packages/ui-library/src/components/text-input/index.ts, packages/ui-library/src/components/textarea/index.stories.ts, packages/ui-library/src/components/textarea/index.ts
=> fix(781):Ensure Consistency between Storybook Documentation and Codebase

docs/GETSTARTED.md
- added open door meeting
- updated Figma access description in access checklist
- added "Onboarding" to project management onboarding checklist headline
- added Design, Developers and Product & Project Management Anchors to ToC
- removed Sales Deck Contributor page from project management onboarding checklist
=> docs: add open door meeting

packages/ui-library/src/utils/typesafe-generic-component-renderer.ts
- render util does not produce malformed HTML anymore when `props` or `htmlAttributes` are empty
Closes #975
=> fix(ui-library, storybook): genericBlrComponentRenderer

packages/js-example-app/src/index.ejs, packages/ui-library/src/components/input-field-number/index.stories.ts, packages/ui-library/src/components/input-field-number/index.test.ts, packages/ui-library/src/components/input-field-number/index.ts, packages/ui-library/src/globals/constants.ts, packages/ui-library/src/globals/types.ts
=> fix(ui-library): ensure property naming number field (831)

packages/ui-library/src/components/button-group/index.stories.ts, packages/ui-library/src/components/button-icon/index.stories.ts, packages/ui-library/src/components/button-text/index.stories.ts, packages/ui-library/src/components/checkbox/index.stories.ts, packages/ui-library/src/components/form-caption-group/index.stories.ts, packages/ui-library/src/components/form-caption-group/index.test.ts, packages/ui-library/src/components/form-caption/index.stories.ts, packages/ui-library/src/components/input-field-number/index.stories.ts, packages/ui-library/src/components/input-field-text/index.stories.ts, packages/ui-library/src/components/radio-group/index.stories.ts, packages/ui-library/src/components/select/index.stories.ts, packages/ui-library/src/components/textarea/index.stories.ts, packages/ui-library/src/components/toggle-switch/index.stories.ts
=> fix(ui): adjust links

packages/ui-library/src/components/textarea/index.css.ts, packages/ui-library/src/components/textarea/index.test.ts, packages/ui-library/src/components/textarea/index.ts
=> fix(ui-library): align counter to right for text area with or without error

.github/workflows/analyze.yml, .github/workflows/compile.yml, .github/workflows/eslint.yml, .github/workflows/test.yml
Apparently yarn just released version 4.1.1 which calculates some package checksums differently than before.
This made all workflows fail during the install phase. To align the yarn versions used in the CI pipeline and in local development, i removed the yarn set version 4.x step from all relevant workflows. corepack will use whatever yarn binary is stored in our repo / configured in our .yarnrc automatically.
=> fix(ci): fix ci package install

packages/js-example-app/src/index.client.ts, packages/js-example-app/src/index.server.ts, packages/ui-library/.babelrc, packages/ui-library/package.json, packages/ui-library/src/components/radio-group/index.css.ts, packages/ui-library/src/components/radio-group/index.stories.ts, packages/ui-library/src/components/radio-group/index.test.ts, packages/ui-library/src/components/radio-group/index.ts, packages/ui-library/src/components/radio-group/renderFunction.ts, packages/ui-library/src/components/radio/index.stories.ts, packages/ui-library/src/components/radio/index.ts, packages/ui-library/src/globals/events.ts, packages/ui-library/src/globals/types.ts, packages/ui-library/src/utils/lit/decorators.ts, packages/ui-library/src/utils/lit/element.ts, packages/ui-library/src/utils/lit/signals.ts, yarn.lock
=> feat(ui-library): radio group - use slots instead of options array

packages/ui-library/src/components/radio-group/index.ts
closes #1139 
Includes the fix for the bug related to size not changing in the radio-group.
=> fix(ui-library): radio group size fix (#1139)

packages/ui-library/src/components/button-text/index.stories.ts, packages/ui-library/src/components/button-text/index.ts, packages/ui-library/src/components/textarea/index.css.ts, packages/ui-library/src/components/textarea/index.stories.ts, packages/ui-library/src/components/textarea/index.test.ts, packages/ui-library/src/components/textarea/index.ts, packages/ui-library/src/foundation/semantic-tokens/form.css.ts, packages/ui-library/src/globals/constants.ts, packages/ui-library/src/globals/types.ts
=> fix(storybook): add functionality

packages/ui-library/src/components/checkbox/index.stories.ts, packages/ui-library/src/components/checkbox/index.ts
=> fix(ui-library): checkbox component fixes

packages/ui-library/src/components/button-icon/index.ts, packages/ui-library/src/components/button-text/index.ts, packages/ui-library/src/components/checkbox/index.ts, packages/ui-library/src/components/counter/index.ts, packages/ui-library/src/components/form-caption/index.ts, packages/ui-library/src/components/form-label/index.ts, packages/ui-library/src/components/icon/index.ts, packages/ui-library/src/components/input-field-number/index.ts, packages/ui-library/src/components/input-field-text/index.css.ts, packages/ui-library/src/components/input-field-text/index.ts, packages/ui-library/src/components/radio-group/index.ts, packages/ui-library/src/components/radio/index.ts, packages/ui-library/src/components/select/index.ts, packages/ui-library/src/components/slider-single-value/range-legend-slider/index.ts, packages/ui-library/src/components/slider-single-value/range-slider/index.ts, packages/ui-library/src/components/slider-two-values/range-legend-min-max-slider/index.ts, packages/ui-library/src/components/slider-two-values/range-min-max-slider/index.ts, packages/ui-library/src/components/tab-bar-item/index.ts, packages/ui-library/src/components/tab-bar/index.stories.ts, packages/ui-library/src/components/tab-bar/index.ts, packages/ui-library/src/components/toggle-switch/index.ts, packages/ui-library/src/components/tooltip/index.test.ts, packages/ui-library/src/components/tooltip/index.ts
=> fix(ui-library): type errors fixed for lint analyze pipeline

.github/workflows/release.yml, docs/DEPLOYMENT.md
=> feat(release): trigger release using release please bot on dev branch
